when:
  - event: [push, manual, cron]
    branch: [master, dev, feature-*]

steps:
  # Create tag from package.version of super productivity app
  - name: prepare-tag
    image: node:20-alpine
    commands:
      - node -p "require('./package.json').version" > .tags

  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: packages/super-sync-server/Dockerfile
      platforms: linux/amd64
      logins:
        - registry: https://git.samurai-planet.top
          username:
            from_secret: forgejo-deploy-user
          password:
            from_secret: forgejo-deploy-token
