when:
  - event: [push, manual, cron]
    branch: master
  - event: manual
    branch: [dev, feature-*]

steps:
  # Create tag from package.version of super productivity app
  - name: prepare-tag
    image: node:20-alpine
    commands:
      - node -p "require('./package.json').version" > .tags
      - echo "Tag value in .tags"
      - cat .tags

  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: github.com/sangdt-spkt/super-productivity
      dockerfile: packages/super-sync-server/Dockerfile
      platforms: linux/amd64
      no_cache: "true"
      logins:
        - registry: https://git.samurai-planet.top
          username:
            from_secret: forgejo-deploy-user
          password:
            from_secret: forgejo-deploy-token
