when:
  - event: [push, manual, cron]
    branch: master

steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: packages/super-sync-server/Dockerfile
      platforms: linux/amd64
      auto_tag: "true"
      default_tag: "19.1.0"
      logins:
        - registry: https://git.samurai-planet.top/
          username:
            from_secret: forgejo-deploy-user
          password:
            from_secret: forgejo-deploy-token
